controller_list:
  - name: fake_base_controller
    joints:
      - odom_y
      - odom_x
      - odom_r
  - name: fake_arm_controller
    joints:
      - arm_lift_joint
      - arm_flex_joint
      - arm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint
      - wrist_ft_sensor_frame_joint
  - name: fake_whole_body_controller
    joints:
      - odom_y
      - odom_x
      - odom_r
      - arm_lift_joint
      - arm_flex_joint
      - arm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint
      - wrist_ft_sensor_frame_joint
  - name: fake_head_controller
    joints:
      - head_pan_joint
      - head_tilt_joint
  - name: fake_gripper_controller
    joints:
      - hand_l_spring_proximal_joint
      - hand_motor_joint
      - hand_r_spring_proximal_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: go
  - group: head
    pose: neutral