base:
  kinematics_solver: cached_ik_kinematics_plugin/CachedTRACKinematicsPlugin
  kinematics_solver_search_resolution: 0.01
  kinematics_solver_timeout: 1.0
  position_only_ik: True
arm:
  kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.01
  kinematics_solver_timeout: 1.0
  position_only_ik: True
whole_body:
  # for position ik
  # kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin   

  # for pose ik
  kinematics_solver: cached_ik_kinematics_plugin/CachedTRACKinematicsPlugin
  kinematics_solver_search_resolution: 0.01
  kinematics_solver_timeout: 1.0
  position_only_ik: True
# head:
#   kinematics_solver: bio_ik/BioIKKinematicsPlugin
#   kinematics_solver_search_resolution: 0.01
#   kinematics_solver_timeout: 0.05
#   position_only_ik: True
# gripper:
#   kinematics_solver: bio_ik/BioIKKinematicsPlugin
#   kinematics_solver_search_resolution: 0.01
#   kinematics_solver_timeout: 0.05
#   position_only_ik: True
